import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const funcionarios = [
    { nome: "ADEMAR TENORIO CAVALCANTE FILHO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ALAN DA SILVA MENDES", area: "SERVIÇOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "AMADEU DE ARAUJO MOURA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ANA IZA DE SOUSA ALENCAR", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ANDERSON TAVARES DANIEL DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ANDRE DE FREITAS RIBEIRO", area: "SERVIÇOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ANDRE LUIZ MENDES CARDOSO", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ANDRE MARCELO FREITAS ALMEIDA", area: "COMERCIAL", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ARTHUR CAVALCANTI TAVARES CORREIA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ARTHUR NOGUEIRA SILVEIRA DE LIMA SANTOS", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ARTHUR URIEL DE SOUZA MOTA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "AUGUSTO CESAR SILVA DE OLIVEIRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "BENJAMIM PEREIRA DE BRITO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "BRUNA GABRIELLY CORREIA FERREIRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "BRUNIELE SANTANA DE FREITAS", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "BRUNO LUIZ DUARTE ALMEIDA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "BRUNO LYRA BEZERRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "CARLA STEPHANIE DUARTE DA SILVA CHIBANTE", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "CARLA CHAGAS DE SOUZA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "CARLA DANIELA SILVA NEVES", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "CARLOS EDUARDO DO NASCIMENTO COIMBRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "CASSIA EMILIANO DE ALBUQUERQUE", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "CICERO CARLOS COSTA NETTO", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "CELSO ANTONIO MOURA DOS SANTOS", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "CLAUDIA LUZIA DA COSTA CURA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "DANIEL CARLOS TIBURCIO DA SILVA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "DANILLO MORAES LIMA DOS SANTOS", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "DIEGO LIMA DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "DOUGLAS GABRIEL RODRIGUES TELES", area: "GENTE & GESTÃO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "DOUGLAS RANYERY SILVA LEITE MORAIS", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "EBERSON NASCIMENTO SANTOS", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "EDIMAR FERREIRA PINTO JUNIOR", area: "DELIVERY", cargo: "Colaborador", emoji: "🎫" },
    { nome: "EVA VICTORIA DA SILVA SOUZA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "EVERTON SANTOS RODRIGUES TORRENTE", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "FABIO ELY CHONKIW ARRUDA", area: "PROJETOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "FABRICIO PAES FERREIRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "FATIMA CAMILA CHAVES ANTUNES", area: "GENTE & GESTÃO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "FELIPE GUIMARAES PACHECO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "FERNANDA MENDONCA DE OLIVEIRA FIGUEIRA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "FERNANDO JOSE DE OLIVEIRA JUNIOR", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "GABRIEL GOMES GONZAGA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "GABRIEL LUIZ DE OLIVEIRA MELLO", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "GENILSON SIMOES CAVALCANTE", area: "DIRETORIA", cargo: "CEO", emoji: "👑" },
    { nome: "GERSON USIEL DE SOUZA MOTA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "GIOVANNI CORTEZ JANKEVICIUS", area: "SERVIÇOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "GLAUCIO SANTOS DE ANDRADE", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "GUILHERME RUTEMBERG FELIX DE LIMA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "HANDSON FREIRE DE LIMA ALVARES", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "HENRI GABRIEL MATOS", area: "SERVIÇOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "HERB LAURENTINO LINS DE MELO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "HUGO DOS SANTOS PORFIRIO", area: "DELIVERY", cargo: "Colaborador", emoji: "🎫" },
    { nome: "IGOR DANIEL DA COSTA SILVA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "INES ALESSANDRA ALVES DE MELO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ISABELE CRISTINE BARCELOS DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JEFERSON RAMOS DE BARROS", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JEFFERSON SALES FERNANDES", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JENILTON ALMEIDA DE JESUS", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JOAO TIAGO RODRIGUES", area: "SUPORTE", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JOAO VICTOR CORDEIRO DA SILVA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JOAO VITOR DA SILVA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JOSE EVERTON TENORIO ALVES", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JOSE HENRIQUE DE PAULA SOARES", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JOSUE NOGUEIRA DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "JUAN CARLOS DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "KARINA DUARTE DE OLIVEIRA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LAIS SANTIAGO FRANCO BRASIL", area: "COMERCIAL", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LARISSA EDUARDA DE ARRUDA MOTTA", area: "COMERCIAL", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LAYLA LUCELY DA SILVA VALLE", area: "GENTE & GESTÃO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LAYSA ALVES PROTASIO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LEANDRO PACHECO ROSAS", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LETICIA VIEIRA CRUZ", area: "SERVIÇOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LIZANDRA BARRETO DIAS", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUAN MEIRELLES DE CARVALHO", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUCAS DOS SANTOS", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUCAS RODRIGUES PINTO", area: "SUPORTE", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUCAS VIANA DE MENDONCA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUCAS VIEIRA AUSTREGESILO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUCAS GOMES MELO NASCIMENTO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUCIANA CABRAL GONCALVES", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUIZ ANTONIO ORNELAS FERNANDES", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUIZ CARLOS SANTOS SOARES DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "LUIZ HENRIQUE SOUZA GOMES DE OLIVEIRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MARCELA NAJARA MARTINS RIBEIRO", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MARCELA PEREIRA DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MARCIA DA SILVA GOMES", area: "PROJETOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MARCIA NASCIMENTO DOS SANTOS", area: "GENTE & GESTÃO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MARCOS RAFAEL MARQUES CAVALCANTI", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MARILIA PIMENTEL BASTOS", area: "ADM/FINANCEIRO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MATEUS DA SILVA MAGALHAES", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MATEUS RESENDE RODRIGUES", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MATHEUS AUGUSTO FERNANDES", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MAURICIO DOS SANTOS SILVA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MIGUEL AUGUST LIMA DE OLIVEIRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MIGUEL OTHON ARAUJO BARBOSA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "MONICA ESPINAL GRAUSO", area: "SERVIÇOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "PAULO SERGIO BERNARDO DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "PEDRO CAETANO ARAUJO ALVES", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "PRISCILA TACIANA DUARTE ALMEIDA", area: "COMERCIAL", cargo: "Colaborador", emoji: "🎫" },
    { nome: "RAI ARAUJO SILVA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "RANIELLE MARINHEIRO DE SA GARCIA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "REBECA LARISSA DA SILVA ALVES", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "RENAN ALVES DA SILVA", area: "GENTE & GESTÃO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "RENAN FELIPE DOS SANTOS PEREIRA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "RENATA MARTINS EVANGELISTA", area: "ADM/FINANCEIRO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "RENATO SANTOS VAZ CURADO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ROSANA CORREA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ROSINEI DE SOUZA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ROUDNELLY LUCAS DE SOUZA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "RUAN DUARTE TEIXEIRA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "SAMUEL MARTINS DA SILVA", area: "PROJETOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "SARAH OLIVEIRA DA SILVA CAMPISTA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "SOLANGE SEBASTIANA CANDIDO", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "STHEFANY XIMENA NUNEZ DA SILVA KOGA", area: "PROJETOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "SUZANY VITORIA DA SILVA SOUSA", area: "SERVIÇOS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "SYLVIA HELENA DE LIMA NERI", area: "ADM/FINANCEIRO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "TASSIA TUANNY MARTINS EVANGELISTA", area: "GENTE & GESTÃO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "THALITA ELLEN DOS REIS BEZERRA", area: "FINANCEIRO/FATURAMENTO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "THAMIRES GOMES MIRANDA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "THIAGO ALMEIDA DE AZEVEDO LERBAK", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "THIAGO FABRICIO DE OLIVEIRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "THIAGO HENRIQUE DE ALMEIDA ESPINHARA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "THYAGO MURILO FERREIRA DOS SANTOS", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "TIAGO PEREIRA NERI DO NASCIMENTO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "VICTOR DE SANTIS CARVALHO CARDOSO", area: "COMERCIAL", cargo: "Colaborador", emoji: "🎫" },
    { nome: "VINICIUS AZEVEDO DOS SANTOS", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "VITORIA RAQUEL NUNES DE MELO", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "WALBER DE PAULA MARQUES DE OLIVEIRA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "WALLACE SOARES DA SILVA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "WANDINGTON LIMA ALVES SILVA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" },
    { nome: "WEMELLY KAUANE DA SILVA MASSU", area: "SISTEMAS", cargo: "Colaborador", emoji: "CAMPUS" },
    { nome: "WENDER DE OLIVEIRA CAMPISTA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "YSADORA MARIANO SILVA DE HOLANDA", area: "OPERAÇÃO BRADESCO", cargo: "Colaborador", emoji: "🎫" },
    { nome: "YURE QUEIROZ SANT ANA", area: "DELIVERY", cargo: "Colaborador", emoji: "🎫" },
    { nome: "ZELIA DE MORAES GOMES TEIXEIRA", area: "SISTEMAS", cargo: "Colaborador", emoji: "🎫" }
  ];

  console.log("🌱 Semeando as 131 figurinhas oficiais tratadas no MongoDB...");

  for (let i = 0; i < funcionarios.length; i++) {
    const f = funcionarios[i];
    const numeroFigurinha = i + 1;

    await prisma.figurinha.upsert({
      where: { numero: numeroFigurinha },
      update: {
        nome: f.nome,
        cargo: f.cargo,
        area: f.area,
        emoji: f.emoji,
        isRara: false, 
        imagem: "",
      },
      create: {
        numero: numeroFigurinha,
        nome: f.nome,
        cargo: f.cargo,
        area: f.area,
        emoji: f.emoji,
        isRara: false,
        imagem: "", 
      },
    });
  }

  console.log(`✅ Seed concluído! ${funcionarios.length} figurinhas cadastradas de forma limpa.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());